SEVERITY_HASH = {
    "(1) Negligible": 1,
    "(2) Minor": 3,
    "(3) Moderate": 2,
    "(4) Major": 4,
    "(5) Catastrophic": 5,
}

PROP_RULE_MAP = [
    {
        "src_prop_path": "fields_System.Id",
        "trgt_prop_path": "id",
        "type": "int",
        "path_separator": "_",
        "map": None,
        "is_path": True,
        "default": 0,
    },
    {
        "src_prop_path": "fields_System.Title",
        "trgt_prop_path": "title",
        "type": "string",
        "path_separator": "_",
        "map": lambda x: x.strip(),
        "is_path": True,
        "default": "",
    },
    {
        "src_prop_path": "fields_System.Tags",
        "trgt_prop_path": "tags",
        "type": "array",
        "path_separator": "_",
        "map": lambda x: list(map(lambda t: t.strip(), x.split(";"))),
        "is_path": True,
        "default": "",
    },
    {
        "src_prop_path": "fields_System.State",
        "trgt_prop_path": "state",
        "type": "string",
        "path_separator": "_",
        "map": None,
        "is_path": True,
        "default": "",
    },
    {
        "src_prop_path": "fields_Custom.SeverityOptionList",
        "trgt_prop_path": "severity",
        "type": "int",
        "path_separator": "_",
        "map": lambda x: SEVERITY_HASH.get(x.strip(), 1) if x and x != "" else 1,
        "is_path": True,
        "default": "(5) Catastrophic",
    },
    {
        "src_prop_path": "fields_Custom.RiskWeighting",
        "trgt_prop_path": "risk_weighting",
        "type": "int",
        "path_separator": "_",
        "map": None,
        "is_path": True,
        "default": 10,
    },
    {
        "src_prop_path": "fields_System.WorkItemType",
        "trgt_prop_path": "type",
        "type": "string",
        "path_separator": "_",
        "map": lambda x: x.strip(),
        "is_path": True,
        "default": "",
    },
    {
        "src_prop_path": "fields_Microsoft.VSTS.Scheduling.RemainingWork",
        "trgt_prop_path": "remaining_work",
        "type": "float",
        "path_separator": "_",
        "map": None,
        "is_path": True,
        "default": -1,
    },
    {
        "src_prop_path": "fields_Microsoft.VSTS.Scheduling.OriginalEstimate",
        "trgt_prop_path": "original_estimate",
        "type": "float",
        "path_separator": "_",
        "map": None,
        "is_path": True,
        "default": -1,
    },
    {
        "src_prop_path": "fields_Microsoft.VSTS.Scheduling.CompletedWork",
        "trgt_prop_path": "completed_work",
        "type": "float",
        "path_separator": "_",
        "map": None,
        "is_path": True,
        "default": -1,
    },
    {
        "src_prop_path": "fields_System.AreaPath",
        "trgt_prop_path": "area_path",
        "type": "string",
        "path_separator": "_",
        "map": None,
        "is_path": True,
        "default": "",
    },
    {
        "src_prop_path": "fields_System.AssignedTo_displayName",
        "trgt_prop_path": "assigned_to",
        "type": "string",
        "path_separator": "_",
        "map": None,
        "is_path": True,
        "default": "",
    },
    {
        "src_prop_path": "fields_System.CreatedDate",
        "trgt_prop_path": "utc_created_at",
        "type": "string",
        "path_separator": "_",
        "map": None,
        "is_path": True,
        "default": "",
    },
]
