version: "2"
services:

  pyzdo-kafka-api:
    networks:
      - pyzdo
    build: ./src/apis/kafka-api
    ports:
      - 8006:8002
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - CLIENT_ID=pyzdo-kafka-api
      - ENVIRONMENT=aks
      - STORE_QUERY_URL=
      - COSMOS_DATABASE_NAME=
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  pyzdo-store-api:
    networks:
      - pyzdo
    build: ./src/apis/store-api
    ports:
      - 8005:8001
    environment:
      - ENVIRONMENT=aks
      - KEY_VAULT_URL=
      - COSMOS_DATABASE_NAME=
      - COSMOS_URL=
      - STORE_QUERY_URL=
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  pyzdo-azdo-proxy-api:
    networks:
      - pyzdo
    build: ./src/apis/azdo-proxy-api
    ports:
      - 5079:5079

  pyzdo-persist-worker:
    networks:
      - pyzdo
    depends_on:
      - pyzdo-store-api
    build: ./src/workers/persist
    environment:
      - WORKER_TOPIC=pyzdo_CMD_PERSIST
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - KAFKA_GROUP_ID=pyzdo-persist-worker-001
      - KAFKA_AUTO_OFFSET_RESET=latest
      - STORE_COMMAND_URL=http://pyzdo-store-api:8001/store/cmd
      - STORE_BULK_COMMAND_URL=http://pyzdo-store-api:8001/store/cmds
      - STORE_QUERY_URL=http://pyzdo-store-api:8001/store/qry
      - ENVIRONMENT=aks
      - DEBUGGING=False
      - COSMOS_DATABASE_NAME=
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  pyzdo-azdo-worker:
    networks:
      - pyzdo
    depends_on:
      - pyzdo-azdo-proxy-api
    build: ./src/workers/azdo
    environment:
      - WORKER_TOPIC=pyzdo_CMD_GATHER
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - KAFKA_GROUP_ID=pyzdo-azdo-worker-001
      - KAFKA_AUTO_OFFSET_RESET=latest
      - DEBUGGING=False
      - PERSIST_TOPIC=pyzdo_CMD_PERSIST
      - PERSIST_URL=http://pyzdo-kafka-api:8002/kafka/topic/publish
      - API_KEY=
      - STORE_QUERY_URL=http://pyzdo-store-api:8001/store/qry
      - ENVIRONMENT=aks
      - KEY_VAULT_URL=
      - COSMOS_DATABASE_NAME=
      - COSMOS_URL=
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  pyzdo-insights-worker:
    networks:
      - pyzdo
    build: ./src/workers/insights
    environment:
      - WORKER_TOPIC=pyzdo_CMD_STRUCTURE
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - KAFKA_GROUP_ID=pyzdo-insights-worker-001
      - KAFKA_AUTO_OFFSET_RESET=latest
      - PERSIST_TOPIC=pyzdo_CMD_PERSIST
      - PERSIST_URL=http://pyzdo-kafka-api:8002/kafka/topic/publish
      - STORE_QUERY_URL=http://pyzdo-store-api:8001/store/qry
      - DEBUGGING=False
      - ENVIRONMENT=aks
      - COSMOS_DATABASE_NAME=
      - COSMOS_URL=
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  pyzdo-azdo-proxy-worker:
    networks:
      - pyzdo
    build: ./src/workers/azdo_proxy
    environment:
      - WORKER_TOPIC=pyzdo_CMD_AZDO_PROXY
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - KAFKA_GROUP_ID=pyzdo-azdo-proxy-worker-001
      - KAFKA_AUTO_OFFSET_RESET=latest
      - PERSIST_TOPIC=pyzdo_CMD_PERSIST
      - PERSIST_URL=http://pyzdo-kafka-api:8002/kafka/topic/publish
      - AZDO_PROXY_BASE_URL=http://pyzdo-azdo-proxy-api:80
      - API_KEY=
      - STORE_QUERY_URL=http://pyzdo-store-api:8001/store/qry
      - ENVIRONMENT=aks
      - DEBUGGING=False
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  pyzdo-ui-api:
    networks:
      - pyzdo
    depends_on:
      - pyzdo-store-api
    build: ./src/apis/ui-api
    ports:
      - 3004:3002
    environment:
      - NODE_ENV=production
      - PORT=3001
      - KAFKA_API_BASE_URL=http://pyzdo-kafka-api:8002
      - STORE_API_BASE_URL=http://pyzdo-store-api:8001

  pyzdo-ui:
    networks:
      - pyzdo
    depends_on:
      - pyzdo-ui-api
    build: ./src/ui/pyzdo-ui
    ports:
      - 8080:8081
    environment:
      - VUE_APP_AZDO_API_KEY=
      - VUE_APP_DEFAULT_QUERY_FOLDER=
      - VUE_APP_UI_API_BASE_URL=http://localhost:3004/ui-api

networks:
  pyzdo:
    driver: bridge
