version: "2"
services:

  project-m-kafka-api:
    networks:
      - project-m
    build: ./src/apis/kafka-api
    ports:
      - 8006:8002
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - CLIENT_ID=projectm-kafka-api
      - ENVIRONMENT=aks
      - STORE_QUERY_URL=
      - COSMOS_DATABASE_NAME=
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  project-m-store-api:
    networks:
      - project-m
    build: ./src/apis/store-api
    ports:
      - 8005:8001
    environment:
      - ENVIRONMENT=aks
      - KEY_VAULT_URL=
      - COSMOS_DATABASE_NAME=
      - COSMOS_URL=
      - STORE_QUERY_URL=
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  project-m-azdo-proxy-api:
    networks:
      - project-m
    build: ./src/apis/azdo-proxy-api
    ports:
      - 5079:5079

  project-m-persist-worker:
    networks:
      - project-m
    depends_on:
      - project-m-store-api
    build: ./src/workers/persist
    environment:
      - WORKER_TOPIC=PROJECTM_CMD_PERSIST
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - KAFKA_GROUP_ID=projectm-persist-worker-001
      - KAFKA_AUTO_OFFSET_RESET=latest
      - STORE_COMMAND_URL=http://project-m-store-api:8001/store/cmd
      - STORE_BULK_COMMAND_URL=http://project-m-store-api:8001/store/cmds
      - STORE_QUERY_URL=http://project-m-store-api:8001/store/qry
      - ENVIRONMENT=aks
      - DEBUGGING=False
      - COSMOS_DATABASE_NAME=
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  project-m-azdo-worker:
    networks:
      - project-m
    depends_on:
      - project-m-azdo-proxy-api
    build: ./src/workers/azdo
    environment:
      - WORKER_TOPIC=PROJECTM_CMD_GATHER
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - KAFKA_GROUP_ID=projectm-azdo-worker-001
      - KAFKA_AUTO_OFFSET_RESET=latest
      - DEBUGGING=False
      - PERSIST_TOPIC=PROJECTM_CMD_PERSIST
      - PERSIST_URL=http://project-m-kafka-api:8002/kafka/topic/publish
      - API_KEY=
      - STORE_QUERY_URL=http://project-m-store-api:8001/store/qry
      - ENVIRONMENT=aks
      - KEY_VAULT_URL=
      - COSMOS_DATABASE_NAME=
      - COSMOS_URL=
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  project-m-insights-worker:
    networks:
      - project-m
    build: ./src/workers/insights
    environment:
      - WORKER_TOPIC=PROJECTM_CMD_STRUCTURE
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - KAFKA_GROUP_ID=projectm-insights-worker-001
      - KAFKA_AUTO_OFFSET_RESET=latest
      - PERSIST_TOPIC=PROJECTM_CMD_PERSIST
      - PERSIST_URL=http://project-m-kafka-api:8002/kafka/topic/publish
      - STORE_QUERY_URL=http://project-m-store-api:8001/store/qry
      - DEBUGGING=False
      - ENVIRONMENT=aks
      - COSMOS_DATABASE_NAME=
      - COSMOS_URL=
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  project-m-azdo-proxy-worker:
    networks:
      - project-m
    build: ./src/workers/azdo_proxy
    environment:
      - WORKER_TOPIC=PROJECTM_CMD_AZDO_PROXY
      - KAFKA_BOOTSTRAP_SERVERS=
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISMS=PLAIN
      - KAFKA_SASL_USERNAME=
      - KAFKA_SASL_PASSWORD=
      - KAFKA_GROUP_ID=projectm-azdo-proxy-worker-001
      - KAFKA_AUTO_OFFSET_RESET=latest
      - PERSIST_TOPIC=PROJECTM_CMD_PERSIST
      - PERSIST_URL=http://project-m-kafka-api:8002/kafka/topic/publish
      - AZDO_PROXY_BASE_URL=http://project-m-azdo-proxy-api:80
      - API_KEY=
      - STORE_QUERY_URL=http://project-m-store-api:8001/store/qry
      - ENVIRONMENT=aks
      - DEBUGGING=False
      - AZURE_CLIENT_ID= 
      - AZURE_CLIENT_SECRET=
      - AZURE_TENANT_ID=

  project-m-ui-api:
    networks:
      - project-m
    depends_on:
      - project-m-store-api
    build: ./src/apis/ui-api
    ports:
      - 3004:3002
    environment:
      - NODE_ENV=production
      - PORT=3001
      - KAFKA_API_BASE_URL=http://project-m-kafka-api:8002
      - STORE_API_BASE_URL=http://project-m-store-api:8001

  project-m-ui:
    networks:
      - project-m
    depends_on:
      - project-m-ui-api
    build: ./src/ui/projectm-ui
    ports:
      - 8080:8081
    environment:
      - VUE_APP_AZDO_API_KEY=
      - VUE_APP_DEFAULT_QUERY_FOLDER=
      - VUE_APP_UI_API_BASE_URL=http://localhost:3004/ui-api

networks:
  project-m:
    driver: bridge
