apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-m-azdo-proxy-worker
  namespace: project-m
  labels:
    app: project-m-azdo-proxy-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-m-azdo-proxy-worker
  template:
    metadata:
      labels:
        app: project-m-azdo-proxy-worker
    spec:
      containers:
        - name: project-m-azdo-proxy-worker
          image: docker.io/project-m/azdo-proxy-worker:1.0.6
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: ""
            - name: KAFKA_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: KAFKA_SASL_MECHANISMS
              value: "PLAIN"
            - name: KAFKA_SASL_USERNAME
              value: ""
            - name: KAFKA_SASL_PASSWORD
              value: ""
            - name: KAFKA_GROUP_ID
              value: "projectm-azdo-proxy-worker-001"
            - name: KAFKA_AUTO_OFFSET_RESET
              value: "latest"
            - name: DEBUGGING
              value: "False"
            - name: WORKER_TOPIC
              value: "PROJECTM_CMD_AZDO_PROXY"
            - name: PERSIST_TOPIC
              value: "PROJECTM_CMD_PERSIST"
            - name: PERSIST_URL
              value: "http://project-m-kafka-api.project-m.svc.cluster.local:8004/kafka/topic/publish"
            - name: STORE_QUERY_URL
              value: "http://project-m-store-api.project-m.svc.cluster.local:8003/store/qry"
            - name: API_KEY
              value: ""
            - name: ENVIRONMENT
              value: "aks"
            - name: KEY_VAULT_URL
              value: ""
            - name: COSMOS_DATABASE_NAME
              value: ""
            - name: COSMOS_URL
              value: ""
            - name: AZURE_CLIENT_ID
              value: ""
            - name: AZURE_CLIENT_SECRET
              value: ""
            - name: AZURE_TENANT_ID
              value: ""
            - name: AZDO_PROXY_BASE_URL
              value: http://project-m-azdo-proxy-api.project-m.svc.cluster.local:5080
