version: "2"
services:

  pyzdo-db:
    networks:
      - pyzdo
    depends_on:
      - broker
    build: ./src/db
    ports:
      - 8091-8097:8091-8097
      - 9123:9123
      - 11207:11207
      - 11210:11210
      - 11280:11280
      - 18091-18097:18091-18097

  pyzdo-kafka-api:
    networks:
      - pyzdo
    depends_on:
      - broker
    build: ./src/apis/kafka-api
    ports:
      - 8006:8002
    environment:
      - KAFKA_BOOTSTRAP_SERVERS:broker:29092
      - CLIENT_ID=pyzdo-kafka-api

  pyzdo-cb-api:
    networks:
      - pyzdo
    depends_on:
      - pyzdo-db
    build: ./src/apis/couchbase-api
    ports:
      - 8005:8001
    environment:
      - COUCHBASE_HOST=pyzdo-db
      - COUCHBASE_USERNAME=root
      - COUCHBASE_PASSWORD=R007__..

  pyzdo-azdo-proxy-api:
    networks:
      - pyzdo
    build: ./src/apis/azdo-proxy-api
    ports:
      - 5079:5079
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - KAFKA_GROUP_ID=pyzdo-azdo-proxy-worker-001
      - WORKER_TOPIC=pyzdo_CMD_AZDO_PROXY
      - PERSIST_TOPIC=pyzdo_CMD_PERSIST
      - PERSIST_URL=http://pyzdo-kafka-api:8002/kafka/topic/publish

  pyzdo-persist-worker:
    networks:
      - pyzdo
    depends_on:
      - broker
      - pyzdo-cb-api
    build: ./src/workers/persist
    environment:
      - KAFKA_GROUP_ID=pyzdo-persist-worker-001
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - WORKER_TOPIC=pyzdo_CMD_PERSIST
      - PERSIST_URL=http://pyzdo-cb-api:8001/cb/cmd
      - BULK_PERSIST_URL=http://pyzdo-cb-api:8001/cb/cmds
      - STORE_QUERY_URL=http://pyzdo-cb-api:8001/cb/qry

  pyzdo-azdo-worker:
    networks:
      - pyzdo
    depends_on:
      - broker
      - pyzdo-azdo-proxy-api
    build: ./src/workers/azdo
    environment:
      - KAFKA_GROUP_ID=pyzdo-azdo-worker-001
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - WORKER_TOPIC=pyzdo_CMD_GATHER
      - PERSIST_URL=http://pyzdo-kafka-api:8002/kafka/topic/publish
      - PERSIST_TOPIC=pyzdo_CMD_PERSIST
      - API_KEY=
      - STORE_QUERY_URL=http://pyzdo-cb-api:8001/cb/qry

  pyzdo-insights-worker:
    networks:
      - pyzdo
    depends_on:
      - broker
    build: ./src/workers/insights
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - KAFKA_GROUP_ID=pyzdo-insights-worker-001
      - WORKER_TOPIC=pyzdo_CMD_STRUCTURE
      - PERSIST_TOPIC=pyzdo_CMD_PERSIST
      - PERSIST_URL=http://pyzdo-kafka-api:8002/kafka/topic/publish
      - STORE_QUERY_URL=http://pyzdo-cb-api:8001/cb/qry

  pyzdo-azdo-proxy-worker:
    networks:
      - pyzdo
    depends_on:
      - broker
    build: ./src/workers/azdo_proxy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - WORKER_TOPIC=pyzdo_CMD_AZDO_PROXY
      - KAFKA_GROUP_ID=pyzdo-azdo-proxy-worker-001
      - PERSIST_TOPIC=pyzdo_CMD_PERSIST
      - PERSIST_URL=http://pyzdo-kafka-api:8002/kafka/topic/publish
      - AZDO_PROXY_BASE_URL=http://pyzdo-azdo-proxy-api:80
      - API_KEY=
      - STORE_QUERY_URL=http://pyzdo-cb-api:8001/cb/qry

  pyzdo-ui-api:
    networks:
      - pyzdo
    depends_on:
      - broker
      - pyzdo-cb-api
    build: ./src/apis/ui-api
    ports:
      - 3004:3002
    environment:
      - PORT=3001
      - NODE_ENV=production
      - KAFKA_API_BASE_URL=http://pyzdo-kafka-api:8002
      - STORE_API_BASE_URL=http://pyzdo-cb-api:8001

  pyzdo-ui:
    networks:
      - pyzdo
    depends_on:
      - pyzdo-ui-api
    build: ./src/ui/pyzdo-ui
    ports:
      - 8080:80
    environment:
      - VUE_APP_AZDO_API_KEY=
      - VUE_APP_DEFAULT_QUERY_FOLDER=
      - VUE_APP_UI_API_BASE_URL=http://localhost:3004/ui-api

networks:
  pyzdo:
    driver: bridge
