# FROM python:3.8-slim
# WORKDIR /app
# COPY ./persist-worker .
# RUN pip install -r requirements.txt
# CMD ["python", "worker.py

FROM python:3.11
WORKDIR /app
COPY ./custom_module.tar.gz /app/
RUN tar -xzvf custom_module.tar.gz && \
  pip install ./custom_module
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
